server:
    port: 8090
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/showroom
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration

  jpa:
    properties:
      hibernate:
        cache:
          use_second_level_cache: false
          use_query_cache: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
        ddl-auto: none
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: frontend
#            admin-url: http://localhost:8080
#            realm: showroom
            scope: openid
            authorization-grant-type: authorization_code
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/showroom


project:
  keycloak:
    client-id: backend
    admin-url: http://localhost:8080
    realm: showroom
    client-secret: 73GOdqwfw1kG349ZZg4IbVU6mmqhDANB
    scope: openid
    grant-type: client_credentials
    issuer-uri: http://localhost:8080/realms/showroom
  allowed-origin: http://localhost:4200


